version: 3

services:
    server:
        build: server
        ports: "${PORT}:80"
    ingester:
        build: ingester
        environment:
            SUBREDDITS: ${SUBREDDITS}
            CLIENT_ID: ${CLIENT_ID}
            SECRET_ID: ${SECRET_ID}
            USERNAME: ${USERNAME}
            PASSWORD: ${PASSWORD}
    redis:
        image: 6-alpine
